#!/usr/bin/env php
<?php

require_once __DIR__ . '/libs/ClassQL/Loader.php';
ClassQL\Loader::register('Parsec', __DIR__ . '/vendor/parsec/libs/Parsec');
ClassQL\Loader::register('ClassQL', __DIR__ . '/libs/ClassQL');

ClassQL\Session::start();
ClassQL\CLI::run();
