
namespace Models;

/**
 * Represents a message sent by the user
 */
Message {

    id int;
    user_id int references users(id);
    message text;

    static findAllByUser($id) : Message[] {
        SELECT * FROM $this WHERE user_id = $id
    }
    
    static create($user_id, $message) : null {
        INSERT INTO $this (user_id, message) VALUES ($user_id, $message)
    }

}

/**
 * hello world
 */
say_hello_to($name) : value {
    SELECT 'hello' || $name
}